# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

games = Game.create([{name: 'Galaga', description: 'A fixed shooter arcade game developed and published by Namco in Japan and published by Midway in North America in 1981. It is the sequel to Galaxian, released in 1979. The gameplay of Galaga puts the player in control of a spacecraft which is situated at the bottom of the screen.' },
                      {name: 'Joust', description: 'An arcade game developed by Williams Electronics and released in 1982. While not the first game to feature two-player cooperative play, Joust was more successful than its predecessors and popularized the concept. The player uses a button and joystick to control a knight riding a flying ostrich. The object is to progress through levels by defeating groups of enemy knights riding buzzards.'},
                      {name: 'Galaga \'88', description: 'is a 1987 fixed shooter arcade game by Namco. It is the third sequel for Galaxian (following Galaga, and Gaplus). It features significantly improved graphics over the previous games in the series, including detailed backgrounds, larger enemies and greater ship details. Although it was well received, fewer cabinets of this game were produced than of Galaga and Gaplus. The game runs on Namco System 1 hardware.'},
                      {name: 'Arkanoid', description: 'an arcade game developed by Taito in 1986.[3] It expanded upon Atari\'s Breakout games of the 1970s by adding power-ups, different types of bricks, a variety of level layouts, and visual layering and depth. The title refers to a doomed "mothership" from which the player\'s ship, the Vaus, escapes. '},
                      {name: 'Asteroids', description: 'an arcade space shooter released in November 1979[1] by Atari, Inc. and designed by Lyle Rains, Ed Logg, and Dominic Walsh. The player controls a spaceship in an asteroid field which is periodically traversed by flying saucers. The object of the game is to shoot and destroy asteroids and saucers while not colliding with either or being hit by the saucers\' counter-fire.'},
                      {name: 'Punch Out', description: 'a boxing arcade game by Nintendo, originally released late 1983.[2][8] It was the first in a series of successful Punch-Out!! games, producing an arcade sequel known as Super Punch-Out!!, a spin-off of the series titled Arm Wrestling, a highly popular version for the NES originally known as Mike Tyson\'s Punch-Out!!, and Super Punch-Out!! for the SNES.'},
                      {name: 'Blazing Star', description: 'a scrolling shooter video game for the Neo Geo home game system. It is the sequel to Pulstar, which was itself a close cousin to the R-Type franchise. A typically hefty Neo Geo ROM at 346 Mb, the game makes extensive use of pseudo-3D prerendered sprites, brief anime and CGI cutscenes (mostly during the intro sequence), and frequent Engrish voice samples and captions.'},
                      {name: 'Breakshot', description: 'Pinball'},
                      {name: 'Burger Time', description: 'a 1982 arcade game created by Data East initially for its DECO Cassette System. The player is chef Peter Pepper, who must walk over hamburger ingredients located across a maze of platforms while avoiding pursuing characters. The game\'s original Japanese title, Hamburger (ハンバーガー?), was changed to BurgerTime before its introduction to the United States.'},
                      {name: 'Centipede', description: 'a vertically oriented shoot \'em up arcade game produced by Atari, Inc. in 1980. The game was designed by Ed Logg and Dona Bailey. The player defends against centipedes, spiders, scorpions and fleas, completing a round after eliminating the centipede that winds down the playing field.'},
                      {name: 'Dig Dug', description: 'an arcade game developed and published by Namco in Japan in 1982. It runs on Namco Galaga hardware, and was published outside Japan by Atari, Inc.'},
                      {name: 'Diner', description: 'a pinball machine produced by Williams in 1990. The objective of the game is to serve all customers in a diner. The table was marketed with the slogan "Its fresh! Its fast! Its hot!".'},
                      {name: 'DonkeyKong', description: 'an arcade game released by Nintendo in 1981. It is an early example of the platform game genre, as the gameplay focuses on maneuvering the main character across a series of platforms while dodging and jumping over obstacles. In the game, Mario (originally named Mr. Video and then Jumpman) must rescue a damsel in distress named Pauline (originally named Lady), from a giant ape named Donkey Kong. '},
                      {name: 'DK Jr.', description: 'a 1982 arcade-style platform video game by Nintendo. It first appeared in arcades, and, over the course of the 1980s, was later released for a variety of platforms, most notably the Nintendo Entertainment System. The game\'s title is written out as Donkey Kong Junior in the North American arcade version and various ports to non-Nintendo systems. Its eponymous star, Donkey Kong Jr., also called simply Junior or abbreviated as DK Jr., is trying to rescue his father Donkey Kong, who has been imprisoned.'},
                      {name: 'Elvira', description: 'a 1989 pinball game designed by Dennis Nordman and Jim Patla and released by Midway (under the Bally label), featuring horrorshow-hostess Elvira. It was followed 1996 by Scared Stiff, also designed by Nordman.'},
                      {name: 'Frogger', description: 'a 1981 arcade game developed by Konami and licensed for North American distribution by Sega-Gremlin and worldwide by Sega itself. It is regarded as a classic from the golden age of video arcade games, noted for its novel gameplay and theme. The object of the game is to direct frogs to their homes one by one by crossing a busy road and navigating a river full of hazards.'},
                      {name: 'Star Trek TNG', description: 'TBD'},
                      {name: 'Super Mario Bros.', description: 'a platform video game developed and published by Nintendo as a pseudo-sequel to the 1983 game, Mario Bros. It was originally released in Japan for the Family Computer on September 13, 1985, and later that year for the Nintendo Entertainment System in North America and Europe on May 15, 1987, and Australia later in 1987.'},
                      {name: 'Ms. Pac-Man', description: 'an arcade video game from the Golden Age. It was produced by Illinois-based Bally/Midway Manufacturing corporation, the North American publisher of Pac-Man. Ms. Pac-Man was released in North America in January 1982,[1] and is one of the most popular arcade video games of all time. This popularity led to its adoption as an official title by Namco, the creator of Pac-Man, which was released in the United States in late 1980. Ms Pac-Man introduced a female protagonist, new maze designs, and several other improved gameplay changes over the original Pac-Man'},
                      {name: 'Mario Bros.', description: 'a platform game published and developed for arcades by Nintendo in 1983. It was created by Shigeru Miyamoto. It has been featured as a minigame in the Super Mario Advance series and numerous other games. Mario Bros. has been re-released for the Wii\'s, Nintendo 3DS\'s, and Wii U\'s Virtual Console services in Japan, North America, Europe and Australia.'},
                      {name: 'Out Run', description: 'an arcade game released by Sega in 1986. It was designed by Yu Suzuki and developed by Sega AM2. The game was a critical and commercial success, becoming one of the best-selling video games of its time,[7][8] winning the Golden Joystick Award for Game of the Year,[8][9] and being listed among the best games of all time. It is notable for its innovative hardware (including a moving cabinet), pioneering graphics and music, innovative features such as offering the player choices in both soundtrack and nonlinear routes, and its strong theme of luxury and relaxation.'},
                      {name: 'Paper Boy', description: 'a 1985 arcade game by Atari Games originally developed in 1984.[1] The players take the role of a paperboy who delivers a fictional newspaper called "The Daily Sun" along a suburban street on his bicycle.[2] The game was ported to numerous video game consoles and personal computers.'},
                      {name: 'Strikers 1945', description: 'a vertically scrolling shoot \'em up arcade game released by Psikyo in 1995. '},
                      {name: 'Pole Position', description: 'an arcade racing video game which was released by Namco in 1982 and licensed to Atari, Inc. for US manufacture and distribution, running on the Namco Pole Position arcade system board. The game was designed by Tōru Iwatani, who had also designed the Gee Bee games and Pac-Man. '},
                      {name: 'Popeye', description: 'a 1983 arcade platform game developed and released by Nintendo based on the Popeye characters licensed from King Features Syndicate and Popeye the Sailor (1960s TV series). Unlike most platform games, the player cannot jump; the only button is "punch."'},
                      {name: 'Castlevania', description: 'a typical platform game in which the player takes the role of Simon Belmont, a descendant of the Belmont clan, a family of vampire hunters. He travels to Dracula\'s demonic castle, Castlevania, and fights his way through the castle destroying Dracula himself and the castle.'},
                      {name: 'SkyCurser', description: 'An arcade game created locally'},
                      {name: 'Bust a Move', description: 'TBD'},
                      {name: 'Space Invaders', description: 'an arcade video game created by Tomohiro Nishikado and released in 1978. It was originally manufactured and sold by Taito in Japan, and was later licensed for production in the United States by the Midway division of Bally. Space Invaders is one of the earliest shooting games and the aim is to defeat waves of aliens with a laser cannon to earn as many points as possible.'},
                      {name: 'Super Hang On', description: 'a motorcycle racing arcade game released by Sega, and the sequel to the acclaimed Hang-On. A version of this game, in the full simulated-motorcycle cabinet used by the original Hang-On, was released in 1991 as Limited Edition Hang-On.'},
                      {name: 'Tapper', description: 'a 1983 arcade game released by Bally Midway. Tapper puts the player in the shoes of a bartender. The player must serve eager, thirsty patrons before their patience expires while collecting empty mugs and tips. The game was produced in association with Budweiser.'},
                      {name: 'Time Pilot', description: 'a multi-directional scrolling shooter and free-roaming aerial combat arcade game designed by Yoshiki Okamoto, released by Konami in 1982, and distributed in the United States by Centuri. Debuting in the golden age of video arcade games, it is a time travel themed game that allowed the player\'s plane to freely move across open air space that can scroll indefinitely in all directions.'},
                      {name: 'Wizard of War', description: 'an arcade game from 1980, developed by Midway. It was ported to the Atari 8-bit family, Commodore 64, Atari 2600, Atari 5200 and renamed to The Incredible Wizard for the Bally Astrocade. The game was released as part of the compilations Midway Arcade Treasures 2 (2004) and Midway Arcade Origins (2012).'},
                      {name: 'Zaxxon', description: 'a 1982 isometric shooter arcade game developed and released by Sega. Some sources claim that Japanese electronics company Ikegami Tsushinki also worked on the development of Zaxxon. The game gives the player the experience of flying a fighter craft through a fortress while shooting at enemy entities (missiles, enemy gunfire, etc.)'},
                      {name: 'Blazing Star', description: 'a scrolling shooter video game for the Neo Geo home game system. It is the sequel to Pulstar, which was itself a close cousin to the R-Type franchise. A typically hefty Neo Geo ROM at 346 Mb, the game makes extensive use of pseudo-3D prerendered sprites, brief anime and CGI cutscenes (mostly during the intro sequence), and frequent Engrish voice samples and captions'}
                    ])
user = User.create([{:email => "bulldogs45@aol.com", :name => "Player1", :password => "yMos7Xogq|u", :password_confirmation => "yMos7Xogq|u"}                    ])

group = Group.create([{:name => "Tappers"}])
group_membership = GroupMembership.create([ {group_id: 1, user_id: 1, commissioner: true}])
scores = Game.all.each do |g|
            score = 100
            10.times do
              Score.create([{user_id: 1, game_id: g.id, group_id: 1, amount: score}])
              score = score + 100
            end
          end
